### ISSUE TITLE
Charset issue

### ISSUE THREAD

**Issue by ComFreek** [UniFormal/IntelliJ-MMT#3]
Charset issue on Windows as mentioned on https://youtrack.jetbrains.com/issue/IDEA-208063.

It may be originating from 

https://github.com/UniFormal/IntelliJ-MMT/blob/1b96df1e3611d49ead6a9be32741a4dd94cf1e91/src/main/scala/info/kwarc/mmt/intellij/language/Files.scala#L18

I'll try integrating Scalastyle later today which should have warned on this line.

**Comment by Jazzpirate** [comment]
Fixed by 77ef8d1c5448824f76fce7ccf696d56829de6f60
